### ISSUE TITLE
Broken config flow `{"message":"Invalid handler specified"}`

### ISSUE THREAD

**Issue by semyonchetvertnyh** [wuwentao/midea_ac_lan#74]
### HA core version

2024.3.3

### Integration version

0.4.1

### Device type and model

Air Conditioner 00000Q1B

### Used App

MSmartHome

### The description of problem

I freshly installed Home Assistant. While I'm trying to install an integration, there is a message:

`Config flow could not be loaded: {"message":"Invalid handler specified"}`

<img width="1512" alt="Screenshot 2024-06-07 at 13 24 28" src="https://github.com/wuwentao/midea_ac_lan/assets/2598761/51d9ff48-81f5-4fb4-9ae5-b1056a2834b1">

### The logs

```
2024-06-07 12:58:12.590 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration midea_ac_lan: cannot import name 'ConfigFlowResult' from 'homeassistant.config_entries' (/usr/src/homeassistant/homeassistant/config_entries.py)
2024-06-07 13:24:18.677 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration midea_ac_lan: cannot import name 'ConfigFlowResult' from 'homeassistant.config_entries' (/usr/src/homeassistant/homeassistant/config_entries.py)
```

**Comment by wuwentao** [comment]
just checked with home assiant 2024.3.3
seems it not have `ConfigFlowResult` class
https://github.com/home-assistant/core/blob/2024.3.3/homeassistant/config_entries.py

seems it available in the next version 2024.4.0
https://github.com/home-assistant/core/blob/2024.4.0/homeassistant/config_entries.py

could you help to upgrade your home assiant version and confirm with it ?
@semyonchetvertnyh

**Comment by semyonchetvertnyh** [comment]
Yeah, I confirm it works correctly in 2024.4.0 version.

**Comment by wuwentao** [comment]
ok, thanks!

**Comment by clbx** [comment]
Running into this on 2024.10

**Comment by wuwentao** [comment]
> Running into this on 2024.10

sorry, what's your meaning? it works well or have new error.
if there is error exist, you can submit a new PR with full debug log file.
if it works well, you can ignore it or give a response.
thanks
